### ISSUE TITLE
Applying CSS efficiently 

### ISSUE THREAD

**Issue by jim-rosales** [ilovemilkk/prj-rev-bwfs-dasmoto#3]
When writing your CSS styles, it is best to try and eliminate any duplicate styles found in your stylesheet as it makes it easier to make changes in the future.

For example here instead of the following:
```CSS
.brushes h2{
    background-color: mediumspringgreen;
    font-family: Helvetica;
    font-size: 32px;
    font-weight: bold;
    color: white;
}
.frames h2{
    background-color: lightcoral;
    font-family: Helvetica;
    font-size: 32px;
    font-weight: bold;
    color: white;
}
.paint h2{
    background-color: skyblue;
    font-family: Helvetica;
    font-size: 32px;
    font-weight: bold;
    color: white;
}
```

You could have done something like this:
```CSS
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes h2 {
    background-color: mediumspringgreen;
}

.frames h2 {
    background-color: lightcoral;
}

.paint h2 {
    background-color: skyblue;   
}
```

This way all your `h2`s inherit the styles they all share and you only need to apply the unique background they all have.

https://github.com/ilovemilkk/prj-rev-bwfs-dasmoto/blob/b852f509b6ca93e58889926a8c9d5fd0fa70df62/DasmotosArts/resources/css/style.css#L10-L30
